name: Project auto-testing
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  LinuxProjectTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Test files
        uses: actions/checkout@v2
        with:
          repository: alonitac/LinuxProject
          ref: main
          path: LinuxProjectOriginal
      - name: Copy test files
        run: |
          mv -f LinuxProjectOriginal/test/* test/
          rm -f -r LinuxProjectOriginal

      - name: Linux Project test
        run: | 
          bash test/test.sh